Todo APP markup
ok-technopolis-2020/Krivitskii_Vadim pull request #1
Opened 2020-10-08 10:51 UTC by OGSegu

2020-10-09 11:48 UTC, fromanywhere requested changes
not bad, нужно больше aria

2020-10-09 11:48 UTC, fromanywhere commented on index.html
> +        <button id="create-btn">Create</button>
нужен ли id?

2020-10-09 11:48 UTC, fromanywhere commented on index.html
> +            <label>CSS</label>
а к чему относится этот label?

2020-10-09 11:48 UTC, fromanywhere commented on index.html
> +        <p id="items-left">3 items left</p>
Я не вполне уверен, что абзац уместен

2020-10-09 12:19 UTC, OGSegu commented on index.html
> +            <label>CSS</label>
Я думал над label for, но мне показалось раз это все обернуто в элемент списка "unchecked-todo", то указывать принадлежность label будет излишне

2020-10-09 12:25 UTC, fromanywhere commented on index.html
> +            <label>CSS</label>
Идея в том, что label расширяет область клика, и чтобы оно заработало, ему нужно это явно указать — либо связкой for-id, либо вложенностью поля внутрь label

2020-10-09 15:04 UTC, OGSegu commented on index.html
> +            <label>CSS</label>
А, теперь понял. Спасибо за пояснение! Исправлю

2020-10-12 09:30 UTC, fromanywhere approved these changes

2020-10-12 17:24 UTC, merged